### ISSUE TITLE
22.2.1: no test suite?

### ISSUE THREAD

**Issue by kloczek** [intel/gmmlib#102]
Doesn;t matter how I've configure sourcetree with `RUN_TEST_SUITE=OFF` or `RUN_TEST_SUITE=ON` ctest is failing because it cannot find any units
```console
[tkloczko@pers-jacek x86_64-redhat-linux-gnu]$ ctest -vv
Test project /home/tkloczko/rpmbuild/BUILD/gmmlib-intel-gmmlib-22.2.1/x86_64-redhat-linux-gnu
No tests were found!!!
```

**Comment by Manish7093** [comment]
Thank you for highlighting this issue. We will address this asap.
Could you please provide more information about this issue. Example : Build steps, OS version.

**Comment by Manish7093** [comment]
> Doesn;t matter how I've configure sourcetree with `RUN_TEST_SUITE=OFF` or `RUN_TEST_SUITE=ON` ctest is failing because it cannot find any units
> 
> ```
> [tkloczko@pers-jacek x86_64-redhat-linux-gnu]$ ctest -vv
> Test project /home/tkloczko/rpmbuild/BUILD/gmmlib-intel-gmmlib-22.2.1/x86_64-redhat-linux-gnu
> No tests were found!!!
> ```

Thank you for highlighting this issue. We will address this asap.
Could you please provide more information about this issue. Example : Build steps, OS version.

**Comment by kloczek** [comment]
I'm using my own distribution which is relatively close to Fedora rawhide.
All wat you need to do is execute cmake with `RUN_TEST_SUITE=OFF` or `RUN_TEST_SUITE=ON`.

**Comment by johnmach** [comment]
Resolved in https://github.com/intel/gmmlib/commit/571b74e1bf27d7409098c7f4c7ff92ffd628615b. Hence closing this Pull Request.
