### ISSUE TITLE
Supported Platforms

### ISSUE THREAD

**Issue by DavidMarec** [intel/gmmlib#11]
## Readme : ##

* Intel Atom and Core Processors supporting Gen9/Gen10 graphics devices
* BDW (Broadwell)
* SKL (Skylake)
* CNL (Cannonlake)
 
What about Apollo Lake architecture ?

-- *The Intel media driver that requires this project for its build is expected to supports APL.* --

**Comment by drprajap** [comment]
GmmLib has similar support as Intel media driver.
It does have support for BXT (Broxton) / APL (Apollolake). 

I will update the ReadMe to reflect this.

**Comment by sameer** [comment]
@drprajap do you know if there are any plans for KBL support?

**Comment by drprajap** [comment]
KBL is Gen9 derivative and we already provide support for it.

**Comment by sameer** [comment]
Does that apply to Media driver as well?

**Comment by drprajap** [comment]
Yes.

**Comment by drprajap** [comment]
ReadMe has been updated to reflect current platform support - [d0a4870](https://github.com/intel/gmmlib/commit/d0a487052757acd205b00c53bfb0c829bfce9700).
Thanks.
