### ISSUE TITLE
CMake Error: The source directory "/home/pixel/gmmlib/Release" does not exist.

### ISSUE THREAD

**Issue by Pixel-47** [intel/gmmlib#110]
cmake [-DCMAKE_BUILD_TYPE= Release | Debug | ReleaseInternal] ..
CMake Error: The source directory "/home/pixel/gmmlib/Release" does not exist.

**Comment by johnmach** [comment]
Hi Pixel-47,

Thank you for reaching out.
Could you please provide more details of the issue and the env which you building gmmlib?

**Comment by johnmach** [comment]
@Pixel-47,

Could you please provide more details such as targeted OS, build flags, and the complete build errors logs so that we can rectify this sooner.

And again, thank you for highlighting your interest in Intel gmmlib.

**Comment by FirewallDaProtogen** [comment]
that error is all it says, as for me, i'm on linux mint. i followed the build instructions the best i could but i am also stuck here

**Comment by johnmach** [comment]
Hi @FirewallDaProtogen,

Thank you or providing the failure logs. This is what I was looking for. Now, I see that the build instructions are wrongly used. That is why I insist for every issue out there, on providing full failure logs as build scenario varies from user to user.

**DCMAKE_BUILD_TYPE** is cmake which is passed to build system to indicate the type of build (Release | Debug | ReleaseInternal) by which the library is to be built and this flag can take only single type at a time.
i.e Either **Release** or **Debug** or **ReleaseInternal** at a time.

The build instruction just consolidates all 3 types just to signify that it supports such types and does not intend to pass all the three at a time. 
Most of the time the Release is used unless you have to debug and do not want compiler optimization. 

So your build command should be just,
`cmake -DCMAKE_BUILD_TYPE=Release ..` or simply `cmake ..` without any type mentioned, by which it builds default as Release type. 

Also we will plan to provide build instructions for each of the case without consolidating to avoid confusion.

**Comment by johnmach** [comment]
Marking this issues as done in c6380d3db11cf3528a02097ce4ed9dab0335dca8 by updating more build details.
