### ISSUE TITLE
[regression] ffmpeg/gstreamer decode some format clips md5 mismatch

### ISSUE THREAD

**Issue by wenqingx** [intel/gmmlib#112]
component: ffmpeg-qsv/ffmpeg-vaapi/gst-va/gst-vaapi/gst-msdk
regression commit:https://github.com/intel/gmmlib/commit/8d74657c32c017571b9ce1bce79b9e47c8b9e9c3 

platform:DG2
kernel:6.8.0-31-generic
OS:VERSION="24.04 LTS (Noble Numbat)"
and the issue should be a pl-common issue.
env:
libva: [6e4167728df6](https://github.com/intel/libva/commit/6e4167728df6bc0512324eefe10b6cf370323b11)
media-driver:[a455c11995ed](https://github.com/intel/media-driver/commit/a455c11995ed)
onevpl:[ca3b340fd20a](https://github.com/intel/libvpl/commit/ca3b340fd20a)
vpl-rt:[07c2b66ec11d](https://github.com/intel/vpl-gpu-rt/commit/07c2b66ec11d)
ffmpeg:https://github.com/intel/cartwheel-ffmpeg/commit/6192122dec2b94053f6c3bb95c39d4ef3e999700

cmdline:
```
ffmpeg -v verbose -hwaccel qsv -init_hw_device qsv=qsv,child_device=/dev/dri/renderD129 -hwaccel_output_format xv30 -hwaccel_flags allow_profile_mismatch -c:v hevc_qsv -i inpit.bin -lavfi 'null' -c:v rawvideo -pix_fmt xv30 -fps_mode passthrough -noautoscale -vframes 9 -y -f tee '[f=md5]pipe:1' 
```

log:
```
[2024-06-27 11:05:09.316490] INFO: slash: DETAIL: md5:expect = e76719a0beaa38274a2ee83809b863f9
[2024-06-27 11:05:09.316545] INFO: slash: DETAIL: md5:actual = 82d4a7fc7f88926eb584ff908cfa5cda
[2024-06-27 11:05:09.316685] INFO: slash: DETAIL: md5:success = False
```

input clips info:
`  Stream #0:0: Video: hevc (Rext), yuv444p10le(tv), 1920x1080, 25 fps, 1200k tbr, 1200k tbn`

**Comment by uartie** [comment]
@wenqingx your media driver build may be stale.  Please recompile media driver with latest gmmlib to see if this resolves your issue.

**Comment by wenqingx** [comment]
> @wenqingx your media driver build may be stale. Please recompile media driver with latest gmmlib to see if this resolves your issue.

thx , closed the issue
