### ISSUE TITLE
Remove ARCH from cmake files and detect architecture asking compiler

### ISSUE THREAD

**Issue by dvrogozh** [intel/gmmlib#17]
Please, remove ARCH from all cmake files. This will break cross compilation support. Instead, detect architecture as follows:
```
if(CMAKE_SIZEOF_VOID_P EQUAL 8)
    message("architecture: 64-bit")
else()
    message("architecture: 32-bit")
endif()
```
CMAKE_SIZEOF_VOID_P will be set for you by cmake: cmake will ask compiler which you are going to use, so you will have 100% guarantee to correctly detect architecture

**Comment by drprajap** [comment]
Issue has been fixed by [72c92c0 ](https://github.com/intel/gmmlib/commit/72c92c0dfa8c7d66cfbad26b96e3df8ddf5ff9ef).
