### ISSUE TITLE
igdgmm.pc file is missing Libs to link with

### ISSUE THREAD

**Issue by dvrogozh** [intel/gmmlib#26]
https://github.com/intel/gmmlib/blob/af2add01200f1d54165732807dfff6415d1e1249/Source/GmmLib/igdgmm.pc.in#L10

This line should actually look as follows:
`Libs: -L${libdir} -ligdgmm`

If it is missing end-user generally speaking may fail to find -ligdgmm on a linking stage if he installed to custom location or uses
`pkg-config --libs igdgmm`
to get link flags and libraries.

**Comment by drprajap** [comment]
This issue has been addressed by commit [d3e1b05](https://github.com/intel/gmmlib/commit/d3e1b053f6639efc25959b0485a0f3def2833354).

Thanks.

**Comment by dvrogozh** [comment]
This works for me, thank you.

By the way if you will write in this way in commit message:
`Fixes: #XXX`
GitHub should automatically close issue once commit is merged....

**Comment by drprajap** [comment]
aah! good to know.. will do that next time..
Thanks.
