### ISSUE TITLE
Do not wipe out compiler flags given by user

### ISSUE THREAD

**Issue by chivakker** [intel/gmmlib#31]
gmmlib cmake is forcing this: 

SET (CMAKE_CXX_STANDARD_LIBRARIES "")
SET (CMAKE_C_STANDARD_LIBRARIES "")
SET (CMAKE_SHARED_LINKER_FLAGS "")
SET (CMAKE_CXX_FLAGS_RELEASEINTERNAL "")
SET (CMAKE_CXX_FLAGS_DEBUG  "")
SET (CMAKE_CXX_FLAGS_RELEASE "")

It should not erase compiler and linker flags coming from user. 

Please remove and reconcile the flags given on Linux.cmake file.

**Comment by dvrogozh** [comment]
The code responsible for this is here and below:
https://github.com/intel/gmmlib/blob/3bbe7417630860d84d5d28799fc7226dd1c5b094/Source/GmmLib/CMakeLists.txt#L382

**Comment by drprajap** [comment]
Yes, we are aware of this change, We had seen issues in past with default settings hence we had to wipe out the default settings to apply specific linker/compiler settings. I am working on resolving the issue and will update it accordingly.

**Comment by dvrogozh** [comment]
@drprajap : this is a blocking issue for the integration of gmmlib on the system level. User-defined settings should be always be preserved.
