### ISSUE TITLE
allow using a system packaged spdlog

### ISSUE THREAD

**Issue by tjaalton** [intel/gmmlib#35]
Debian already has libspdlog-dev which includes all the headers, so to avoid duplicate work I'd rather just use that and not ship those files with gmmlib.

**Comment by tjaalton** [comment]
looks like only the include in Source/GmmLib/Utility/GmmLog/GmmLog.h needs to be changed, and then maybe let cmake check first which one to use

**Comment by dvrogozh** [comment]
@tjaalton: can you, please, name few include files which gmmlib installs and which are already included in libspdlog-dev?

**Comment by tjaalton** [comment]
everything under <includedir>igdgmm/GmmLib/Utility/GmmLog/spdlog/*

**Comment by dvrogozh** [comment]
Got it! Thank you for pointing this out. Yes, definitely worth to be reviewed/refactored/improved. CentOS 7.5 also looks to have this (and I would guess Fedora and RedHat as well):
```
# yum search spdlog
spdlog-devel.x86_64 : Development files for spdlog
```
