### ISSUE TITLE
19.1.2: CMake: incorrect assignment of default GMMLIB_API_PATCH_VERSION

### ISSUE THREAD

**Issue by mkszuba** [intel/gmmlib#47]
Hello,

At the moment, Source/GmmLib/CMakeLists.txt calls

`set(GMMLIB_API_PATCH_VERSION PATCH_VERSION)`

if GMMLIB_API_PATCH_VERSION has not been explicitly defined. This results in the shared library being named literally "libigdgmm.so.9.0.PATCH_VERSION".

The simplest way of fixing this seems to be to change the aforementioned assignment to

`set(GMMLIB_API_PATCH_VERSION "${PATCH_VERSION}")`

**Comment by johnbash** [comment]
Fixed at [https://github.com/intel/gmmlib/commit/8feb8385a3c9bf82ae337e97578a0f478fcbddf7](url)

**Comment by johnbash** [comment]
Fixed at [https://github.com/intel/gmmlib/commit/8feb8385a3c9bf82ae337e97578a0f478fcbddf7](url)
