### ISSUE TITLE
Never used variable 'Mip4Height'

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [intel/gmmlib#50]
https://github.com/intel/gmmlib/blob/e834bcd677382fbebb7749ccbd678d86a82bffd3/Source/GmmLib/ULT/GmmGen9ResourceULT.cpp#L749

**Comment by Manish7093** [comment]
Fixed in 3c41a692b68df52382f0e9ba5ce5e955ed67908f

**Comment by johnmach** [comment]
Resolved in https://github.com/intel/gmmlib/commit/3c41a692b68df52382f0e9ba5ce5e955ed67908f
