### ISSUE TITLE
‘-Werror=implicit-function-declaration’ is not valid for C++

### ISSUE THREAD

**Issue by sebastinas** [intel/gmmlib#52]
GCC 9 emits the following new warning:

```
cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++
```

Please remove the flag for C++ code.

**Comment by baybal** [comment]
implicit-function-declaration makes no sense on gcc 9+ for c++

**Comment by edwarddavidbaker** [comment]
Looks like this was removed in a3fe3ac79 .
