### ISSUE TITLE
userptr: provide uAPI to pass pitch to describe memory allocation done by the user

### ISSUE THREAD

**Issue by dvrogozh** [intel/gmmlib#55]
Reporting as a follow up for intel/media-driver#746.

Scenario is:
1. End-user allocates surface in system memory (basically via malloc)
2. User tries to create VASurface via userptr path passing https://github.com/intel/libva/blob/4b1bc91936ef0f8c3f0e22be0fccd401770879eb/va/va.h#L1379 to the media driver
3. Media driver requests gmmlib to validate that user allocation complies to padding/alignment expectations
4. gmmlib validates user input and returns gmm resource object or `NULL` if allocation is not compliant

The problem is that media driver can't comprehensively describe end-user memory allocation. One of the issues is that there is no way to specify a pitch. Please, provide uAPI to do that.

**Comment by johnbash** [comment]
Merged change here: 1598c1b
