### ISSUE TITLE
userptr: no API to describe region of interest for YUV packed surfaces

### ISSUE THREAD

**Issue by dvrogozh** [intel/gmmlib#56]
Reported as follow up of intel/media-driver#747

YUV packed surfaces require additional row + 16 bytes padding per the note here:
https://github.com/intel/gmmlib/blob/master/Source/GmmLib/Texture/GmmGen9Texture.cpp#L869

Unfortunately, there is no uAPI for the media driver to notify gmmlib that any padding rows are actually available. Please, provide such an uAPI or remove the above restriction if possible.

**Comment by johnbash** [comment]
Merged change here: 1598c1b
