### ISSUE TITLE
Never used variable 'TileWidth'

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [intel/gmmlib#60]
https://github.com/intel/gmmlib/blob/f78be970a6c3aef6d0347159f9c3f250421af16c/Source/GmmLib/Texture/GmmTextureAlloc.cpp#L1316

**Comment by Manish7093** [comment]
Fixed in 895ad6d65c9794859d907df64591121c8e01f22d

**Comment by johnmach** [comment]
Resolved in https://github.com/intel/gmmlib/commit/895ad6d65c9794859d907df64591121c8e01f22d
