### ISSUE TITLE
FindThreads.cmake:121 (CHECK_INCLUDE_FILE)

### ISSUE THREAD

**Issue by th0ma7** [intel/gmmlib#66]
Trying to compile version 19.4.1 on linux.
Was facing the issue while trying to cross-compile using `spksrc` toolstack.
I ended-up giving a try on a plain ubuntu and getting the exact same error.
Help on this would be much appreciated.

I'm unable to get passed the `cmake` portion as I always end-up getting the following error:
```
...
platform: Linux
source_dir: /home/whoami/gmmlib-intel-gmmlib-19.4.1/Source/GmmLib
arch: 64
build type: Release
SourceConfiguration:
CommonDir: /home/whoami/gmmlib-intel-gmmlib-19.4.1/Source/Common
IncDir: /home/whoami/gmmlib-intel-gmmlib-19.4.1/Source/inc
MOCS table: Static
CMake Error at /usr/share/cmake-3.13/Modules/CheckIncludeFile.cmake:50 (configure_file):
  configure_file attempted to configure a file:
  /home/whoami/gmmlib-intel-gmmlib-19.4.1/CMakeFiles/CMakeTmp/CheckIncludeFile.c
  into a source directory.
Call Stack (most recent call first):
  /usr/share/cmake-3.13/Modules/FindThreads.cmake:121 (CHECK_INCLUDE_FILE)
  Source/GmmLib/CMakeLists.txt:440 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/whoami/gmmlib-intel-gmmlib-19.4.1/CMakeFiles/CMakeOutput.log".
```

**Comment by th0ma7** [comment]
forgot a simple `mkdir build && cd build`.
issue closed.

**Comment by vivek9746** [comment]
Hey, I'm facing a similar issue, can you explain how you solved it?

**Comment by wdeasy** [comment]
> Hey, I'm facing a similar issue, can you explain how you solved it?

I just had this problem. On step #4, "cmake [-DCMAKE_BUILD_TYPE= Release | Debug | ReleaseInternal] [-DARCH= 64 | 32] .." 

I had left out the ".." at the end of the line.

**Comment by mrbarletta** [comment]
For me it was this command
`~/gmmlib/build$  cmake -S .. `

otherwise it didn't work
