### ISSUE TITLE
Switch to CMAKE_BUILD_TYPE from BUILD_TYPE

### ISSUE THREAD

**Issue by JacekDanecki** [intel/gmmlib#70]
gmmlib uses BUILD_TYPE variable to select build type. Can you switch to use CMAKE_BUILD_TYPE instead of?
Currently when we run:
```
cmake ../gmmlib -DCMAKE_BUILD_TYPE=Debug
```
gmmlib will be built as Release
```
*BUILD_TYPE not defined, default to: release
```

**Comment by johnmach** [comment]
This is resolved in https://github.com/intel/gmmlib/commit/19963011a40afd62c2a90e54d750fc3c60482ab7
