### ISSUE TITLE
Refer the Readme, cmake option 'DARCH' and 'DCMAKE_BUILD_TYPE' is Invalid 

### ISSUE THREAD

**Issue by zongxin1993** [intel/gmmlib#76]
Refer the Readme.
**cmake [-DCMAKE_BUILD_TYPE= Release | Debug | ReleaseInternal] [-DARCH= 64 | 32] ..**

But from the [https://github.com/intel/gmmlib/blob/master/Source/GmmLib/CMakeLists.txt](url) source file.

'CMAKE_BUILD_TYPE' should be 'BUILD_TYPE' ,and the param (Release | Debug | ReleaseInternal)  ， ‘Release’ and 'Debug '  is no difference.

'ARCH' is not checked in CmakeList.

**Comment by johnmach** [comment]
In https://github.com/intel/gmmlib/commit/19963011a40afd62c2a90e54d750fc3c60482ab7, Support for CMAKE_BUILD_TYPE is introduced and BUILD_TYPE is retained. Users can still use both flags. BUILD_TYPE is subject to deprecation once usage of CMAKE_BUILD_TYPE stabilizes. 

In https://github.com/intel/gmmlib/commit/72c92c0dfa8c7d66cfbad26b96e3df8ddf5ff9ef, ARCH is read from compiler.
