### ISSUE TITLE
License header for g_gfxDebug.h

### ISSUE THREAD

**Issue by cdotstout** [intel/gmmlib#85]
We're interested in using gmmlib as part of a Fuchsia driver for media acceleration on Intel hardware.

The license header in this file:
https://github.com/intel/gmmlib/blob/master/Source/util/g_gfxDebug.h

doesn't match the overall project license as specified here:
https://github.com/intel/gmmlib/blob/master/LICENSE.md

Is there a reason for the discrepancy or is it possible to update the license header in g_gfxDebug.h to match?

Thanks.

**Comment by johnmach** [comment]
Hi Stout,

This is most likely a miss during the release. Will address this soon.

**Comment by johnmach** [comment]
This is fixed in https://github.com/intel/gmmlib/pull/59
Hence closing this issue.
