### ISSUE TITLE
Upcoming Gmmlib ABI break Changes

### ISSUE THREAD

**Issue by johnmach** [intel/gmmlib#92]
The functionality of the library is enhanced by adding more support to the discrete platforms along with the existing support for integrated platforms. 

These enhanced functionality changes breaks existing backward compatibility in the binary and hence results in ABI break. These changes are necessary to support both integrated and discrete adapters at the same time. 

Since Gmmlib got the opportunity for an ABI break, Gmmlib is planning to remove the older interface as well which is not usable.

The required changes are listed in  https://github.com/intel/gmmlib/pull/91

**Comment by kwizart** [comment]
Can you clarify why this change was introduced in 21.3 instead of using 22.1 ?
As I understood, 21.3 should have been considered as a bugfix branch as such ABI changes should not be done there...

Thanks for your clarification.

**Comment by johnmach** [comment]
Thank you for reaching to us and highlighting your expectations. We did not realize that 21.3.x releases were considered as a release series which should preserve same ABI and introduce only critical bug fixes.

To resolve the situation:
1. We acknowledge that 21.3.x is a release series with stable backward compatible ABI/API and critical bug fixes only.
2. We just released [intel-gmmlib-21.3.5](https://github.com/intel/gmmlib/releases/tag/intel-gmmlib-21.3.5) (which is retagged [21.3.3](https://github.com/intel/gmmlib/releases/tag/intel-gmmlib-21.3.3)) to return 21.3.x series to the old ABI/API
3. Please, don't use [intel-gmmlib-21.3.4](https://github.com/intel/gmmlib/releases/tag/intel-gmmlib-21.3.4) as it has API/ABI break in 21.3.x series, use [intel-gmmlib-21.3.5](https://github.com/intel/gmmlib/releases/tag/intel-gmmlib-21.3.5).

Secondly, we are changing tags naming scheme as follows:
1. We step out from `YEAR.QUARTER.RELEASE_NUMBER` scheme
2. New naming scheme will be: `TAG=(API_MAJOR+10).API_MINOR.RELEASE_NUMBER`
3. So, `TAGS=(API_MAJOR+10).API_MINOR.x` will be stable release series with the same API and ABI version, only bug fixes
4. On potential API/ABI breaks: `API: 12.x -> 13.0` and `TAG=23.0.0`

We ‘ve tagged [intel-gmmlib-22.0.0](https://github.com/intel/gmmlib/releases/tag/intel-gmmlib-22.0.0) following the new scheme. Mind that 22.0.0 has API/ABI break comparing to 21.3.x release series.

**Comment by johnmach** [comment]
This issue is resolved by the commit c239ff1d7c87017b4a73e8b7a3dcad53d8ab840c tagged with `intel-gmmlib-22.0.0`
